name: Deploy Laravel App via SSH

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
            cd ${{ secrets.DEPLOY_PATH }}

            echo "→ Pulling latest changes..."
            git pull origin main

            echo "→ Installing composer dependencies..."
            composer install --no-interaction --prefer-dist --optimize-autoloader

            echo "→ Running Laravel optimizations..."
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            echo "→ Restarting PHP-FPM..."
            sudo systemctl reload php8.3-fpm
EOF
